# Generated by Django 5.1.2 on 2024-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_profile_age_profile_drink_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
